//Crie a const para a frase aqui
const frase = ("Jorge tem uma casa verde e com portão azul, com os dizeres:\"BOAS VINDAS, mas não deixe o gato sair\"")
const novaFrase = frase.replaceAll("verde","rosa").replaceAll("azul","laranja")
const fraseMaiuscula1 = ("mas não deixe o gato sair")
const novaFraseMaiuscula1 = novaFrase.replaceAll("mas não deixe o gato sair" , "MAS NÃO DEIXE O GATO SAIR")
console.log(frase)
console.log(novaFrase)
console.log(novaFrase.includes("verde"))
console.log(novaFrase.includes("laranja"))
console.log(novaFraseMaiuscula1)